<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class LandingPageSeeder extends Seeder
{
    public function run()
    {
        $this->db->table('landing_pages')->insertBatch([
            [
                'slug'                => 'limited-edition-crystal-mage',
                'title'               => 'The Crystal Mage - Limited Edition',
                'meta_description'    => 'Own this stunning AI-generated fantasy artwork. Limited copies available at a special launch price.',
                'keywords'            => 'crystal mage, fantasy art, AI art, digital art, limited edition',
                'headline'            => "Discover <span>The Crystal Mage</span>\nA Masterpiece of AI Art",
                'subheadline'         => 'Limited edition digital artwork — high resolution, commercially licensed, instant download.',
                'old_price_of_seminar' => '₹9,999',
                'new_price_of_seminar' => '₹4,999',
                'price'               => 4999.00,
                'redirection_link'    => site_url('/shop/the-crystal-mage'),
                'language'            => 'en',
                'reserv_seat_messsage' => '⚠️ Only 5 copies remaining at this price',
                'timer_time_in_minutes' => 45,
                'intro_title'         => 'What Makes This Artwork Special',
                'intro_content'       => "Every piece in our collection is generated using cutting-edge AI models, then carefully curated and enhanced by our team. The Crystal Mage features intricate crystalline details, ethereal lighting, and a captivating fantasy aesthetic that will transform any space.",
                '_intro_join_button_text' => 'Buy Now - ₹4,999',
                'workshop_section_title' => 'What You\'ll Get',
                'workshop_title_1'    => 'High Resolution PNG',
                'workshop_details_1'  => '4096x4096 px, 300 DPI — ready for print or digital display.',
                'workshop_title_2'    => 'Commercial License',
                'workshop_details_2'  => 'Use in your projects, merchandise, or client work. Full commercial rights included.',
                'workshop_title_3'    => 'Instant Download',
                'workshop_details_3'  => 'Access your files immediately after purchase. No waiting, no shipping.',
                'workshop_title_4'    => 'Multiple Formats',
                'workshop_details_4'  => 'Comes in PNG, JPEG, and TIFF formats for maximum flexibility.',
                'testimonial_section_title' => 'What Our Customers Say',
                'footer_section_title'     => 'Ready to Own This Masterpiece?',
                'footer_section_subtitle'  => 'Join thousands of satisfied collectors who trust AI Art Store for premium digital artwork.',
                'footer_link_title_1' => 'Terms & Conditions',
                'footer_link_1'       => site_url('/terms'),
                'footer_link_title_2' => 'Privacy Policy',
                'footer_link_2'       => site_url('/privacy'),
                'footer_link_title_3' => 'Refund Policy',
                'footer_link_3'       => site_url('/refund'),
                'footer_link_title_4' => 'FAQ',
                'footer_link_4'       => site_url('/faq'),
                'status'              => 'active',
            ],
            [
                'slug'                => 'ai-art-bundle-deal',
                'title'               => 'Starter Artist Bundle - 70% Off',
                'meta_description'    => 'Get 5 premium AI artworks plus a complete guide. Everything you need to start your digital art collection.',
                'keywords'            => 'AI art bundle, digital art collection, starter pack, art bundle deal',
                'headline'            => "The Ultimate <span>AI Art Starter Bundle</span>\n5 Artworks + Complete Guide",
                'subheadline'         => 'Everything you need to kickstart your digital art collection. Valued at ₹6,999 — yours for just ₹199!',
                'old_price_of_seminar' => '₹6,999',
                'new_price_of_seminar' => '₹199',
                'price'               => 199.99,
                'redirection_link'    => site_url('/shop/starter-artist-bundle'),
                'language'            => 'en',
                'reserv_seat_messsage' => '🔥 Special launch offer — 100 bundles sold today!',
                'timer_time_in_minutes' => 30,
                'intro_title'         => 'Why This Bundle?',
                'intro_content'       => "Whether you're a designer looking for fresh素材, a content creator needing unique visuals, or just starting your art collection — this bundle gives you incredible variety at an unbeatable price. Includes 5 premium AI artworks across different styles plus a comprehensive guide to AI art generation.",
                '_intro_join_button_text' => 'Grab the Bundle - ₹199',
                'workshop_section_title' => 'Bundle Includes',
                'workshop_title_1'    => '5 Premium Artworks',
                'workshop_details_1'  => 'Curated selection across fantasy, abstract, landscape, and futuristic styles.',
                'workshop_title_2'    => 'AI Art Guide PDF',
                'workshop_details_2'  => '50+ page guide covering prompt engineering, tools, and techniques.',
                'workshop_title_3'    => 'Commercial License',
                'workshop_details_3'  => 'Full commercial usage rights for all included artworks.',
                'workshop_title_4'    => 'Bonus Content',
                'workshop_details_4'  => 'Exclusive presets and prompt templates worth ₹999 FREE.',
                'testimonial_section_title' => 'Loved by Creators',
                'footer_section_title'     => 'Don\'t Miss This Deal',
                'footer_section_subtitle'  => 'Over 1,000 bundles already sold. This price won\'t last.',
                'footer_link_title_1' => 'Terms & Conditions',
                'footer_link_1'       => site_url('/terms'),
                'footer_link_title_2' => 'Privacy Policy',
                'footer_link_2'       => site_url('/privacy'),
                'footer_link_title_3' => 'Refund Policy',
                'footer_link_3'       => site_url('/refund'),
                'footer_link_title_4' => 'FAQ',
                'footer_link_4'       => site_url('/faq'),
                'status'              => 'active',
            ],
            [
                'slug'                => 'enchanted-forest-offer',
                'title'               => 'Enchanted Forest - Nature\'s Magic',
                'meta_description'    => 'Immerse yourself in this magical AI-generated forest scene. Perfect for wall art, meditation, and creative projects.',
                'keywords'            => 'enchanted forest, nature art, AI landscape, magical forest, digital wallpaper',
                'headline'            => "Step Into the <span>Enchanted Forest</span>\nWhere Nature Meets AI Magic",
                'subheadline'         => 'A breathtaking AI-generated forest scene with glowing flora, mystical lighting, and serene atmosphere.',
                'old_price_of_seminar' => '₹5,999',
                'new_price_of_seminar' => '₹2,999',
                'price'               => 2999.00,
                'redirection_link'    => site_url('/shop/enchanted-forest'),
                'language'            => 'en',
                'reserv_seat_messsage' => '🌿 Special nature lover\'s price — limited time only',
                'timer_time_in_minutes' => 60,
                'intro_title'         => 'The Magic of AI Nature Art',
                'intro_content'       => "Our AI models have been trained on millions of forest photographs and fantasy illustrations to create this unique piece. Every leaf, every light particle, and every shadow has been generated and refined to create a scene that feels both familiar and otherworldly. Perfect for large format printing or digital wallpaper.",
                '_intro_join_button_text' => 'Get It Now - ₹2,999',
                'workshop_section_title' => 'Product Details',
                'workshop_title_1'    => 'Ultra HD Resolution',
                'workshop_details_1'  => '4096x4096 px — perfect for wall art, posters, and desktop backgrounds.',
                'workshop_title_2'    => 'Color Profiles',
                'workshop_details_2'  => 'Includes sRGB and Adobe RGB versions for accurate print reproduction.',
                'workshop_title_3'    => 'Ready to Print',
                'workshop_details_3'  => 'Optimized for print up to 24x24 inches at 300 DPI.',
                'workshop_title_4'    => 'Peaceful Vibe',
                'workshop_details_4'  => 'Calming color palette — ideal for meditation spaces, bedrooms, or offices.',
                'testimonial_section_title' => 'Customer Reviews',
                'footer_section_title'     => 'Bring the Forest Home',
                'footer_section_subtitle'  => "Transform your space with the magic of AI-generated nature art.",
                'footer_link_title_1' => 'Terms & Conditions',
                'footer_link_1'       => site_url('/terms'),
                'footer_link_title_2' => 'Privacy Policy',
                'footer_link_2'       => site_url('/privacy'),
                'footer_link_title_3' => 'Refund Policy',
                'footer_link_3'       => site_url('/refund'),
                'footer_link_title_4' => 'FAQ',
                'footer_link_4'       => site_url('/faq'),
                'status'              => 'active',
            ],
        ]);

        echo "Inserted 3 landing pages.\n";
    }
}
